apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: voting-service-route
  namespace: voting
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`voting.k8s.com`)
    priority: 10
    observability:
      accesslogs: true
      metrics: true
      tracing: true
    services:
    - kind: Service
      name: voting-service
      namespace: voting
      port: 80
